/' http://plantuml.com/class-diagram '/ 
@startuml CG_Biblioteca_Completo

title Diagrama de Classes - CG_Biblioteca Completo
footer Grupo GCG - [[http://gcg.inf.furb.br]]

!include PlantUML/CG_Biblioteca/BBox.puml
!include PlantUML/CG_Biblioteca/CameraOrtho.puml
!include PlantUML/CG_Biblioteca/CameraPerspective.puml
!include PlantUML/CG_Biblioteca/Cor.puml
!include PlantUML/CG_Biblioteca/Matematica.puml
!include PlantUML/CG_Biblioteca/Ponto4D.puml
!include PlantUML/CG_Biblioteca/Transformacao4D.puml

@enduml
