/' http://plantuml.com/class-diagram '/ 
@startuml CG_N2_Completo

title Diagrama de Classes - CG_N2 Completo
footer Grupo GCG - [[http://gcg.inf.furb.br]]

!include ../../../CG_Biblioteca/plantUML/CG_Biblioteca.puml

!include ./plantuml/include.puml

@enduml
